[package]
authors = ["Zhenyuan Zhang <cryscan@umich.edu>"]
categories = ["science", "text-processing"]
description = "An implementation of the RWKV language model in pure WebGPU."
edition = "2021"
exclude = ["assets/", "crates/", "screenshots/"]
homepage = "https://github.com/cryscan/web-rwkv"
keywords = ["deep-learning", "language", "model", "rwkv"]
license = "MIT OR Apache-2.0"
name = "web-rwkv-puzzles"
repository = "https://github.com/cryscan/web-rwkv"
version = "0.1.0"

[package.metadata.wasm-pack.profile.release]
wasm-opt = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
base64 = "0.22.1"
bitflags = "2.9"
bytemuck = { version = "1.23", features = ["extern_crate_alloc"] }
cbor4ii = { version = "1.0.0", features = ["serde1"] }
derive-getters = "0.5"
fastrand = { version = "2.3", features = ['js'] }
flume = "0.11"
futures = "0.3.31"
half = { version = "2.4", features = ["bytemuck"] }
image = "0.25.5"
itertools = "0.14"
js-sys = "0.3"
lazy_static = "1.5"
log = "0.4"
qp-trie = "0.8"
regex = "1.10"
safetensors = "0.6"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uid = "0.1"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = ["Blob", "console"] }

[dependencies.web-rwkv]
default-features = false
features = ["web"]
# path = "../web-rwkv"
version = "0.10.15"

[lib]
crate-type = ["cdylib", "rlib"]
